# Spring Boot configuration
spring:
  main:
    lazy-initialization: false

feign:
  okhttp:
    enabled: true
  httpclient:
    connection-timeout: 5000
    max-connections: 400
    max-connections-per-route: 400
  hystrix:
    enabled: true

hystrix:
  threadpool:
    default:
      # Maximum number of concurrent requests when using thread pools (Default: 10)
      coreSize: 100
      # Maximum LinkedBlockingQueue size - -1 for using SynchronousQueue (Default: -1)
      maxQueueSize: -1
      # Queue size rejection threshold (Default: 5)
      queueSizeRejectionThreshold: 5

server:
  port: ${SERVER_PORT:8084}
  eureka:
    instance:
      prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}
      instanceId: ${spring.application.name}-${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
