# Spring Boot configuration
spring:

  # Database
  data:
    mongodb:
      authentication-database: ${MONGO_AUTH_DB:admin}
      password: ${MONGO_PSWD:secret}
      username: ${MONGO_USER:mongoadmin}
      database: ${MONGO_DB:aperitech}
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27018}

server:
  port: ${SERVER_PORT:8082}
  eureka:
    instance:
      prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:false}
      instanceId: ${spring.application.name}-${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
