server:
  port: ${PORT:8090}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:reactive-aggregator}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      reactive:
        enabled: true